User.create(username: 'Garth', password: 'password')
User.create(username: 'Franklin', password: 'Bado')
User.create(username: 'Franklin', password: 'Bado')
User.create(username: 'Franklin', password: 'Bado')
User.create(username: 'Franklin', password: 'Bado')
User.create(username: 'Franklin', password: 'Bado')
Profile.create(first_name: 'Garth', last_name: 'Puckerin', birthday: '2018-06-15', email: '10', telephone: '',user_id: 1)
Profile.create(first_name: 'Franklin', last_name: 'Bado', birthday: '2018-11-15', email: '10', telephone: '', user_id: 2)
Profile.create(first_name: 'Red', last_name: 'Herring', age: 28, salary: 65000, education: 'PhD', cohort_id: 2)
Profile.create(first_name: 'Miller', last_name:'Thyme', age: 30, salary: 50000, education: 'Masters', cohort_id: 1)
Profile.create(first_name: 'Red', last_name: 'Herring', age: 28, salary: 65000, education: 'PhD', cohort_id: 2)
Profile.create(first_name: 'Red', last_name: 'Herring', age: 28, salary: 65000, education: 'PhD', cohort_id: 2)
Profile.create(first_name: 'Red', last_name: 'Herring', age: 28, salary: 65000, education: 'PhD', cohort_id: 2)
Post.create(first_name: 'Red', last_name: 'Herring', age: 28, salary: 65000, education: 'PhD', cohort_id: 2)
Post.create(first_name: 'Red', last_name: 'Herring', age: 28, salary: 65000, education: 'PhD', cohort_id: 2)
Post.create(student_id: 1, cohort_id: 1)
Post.create(student_id: 1, cohort_id: 2)
Post.create(student_id: 2, cohort_id: 1)